name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to download'
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: 'The result of the deployment'
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some_secret:
    #     required: true
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-output.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List contents
        run: ls
      - name: Output information
        run: echo "Deploying & uploading"
      - name: Set output
        id: set-output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
