name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to download'
        required: true
        default: 'dist'
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List contents
        run: ls
      - name: Output information
        run: echo "Deploying & uploading"
